name: NoxesiumAPI
version: '3.1.0'
main: me.iris.noxesiumapi.NoxesiumAPIPlugin
api-version: '26.1.2'
authors: [ Iris ]
description: A plugin and API making communicating with Noxesium clients easier.
website: https://github.com/Irisufus/NoxesiumAPI
