name: NoxesiumAPI
version: '3.0.0'
main: me.iris.noxesiumapi.NoxesiumAPIPlugin
api-version: '1.21.11'
authors: [ Iris ]
description: A plugin and API making communicating with Noxesium clients easier.
website: https://github.com/Irisufus/NoxesiumAPI
