name: NoxesiumAPI
version: '2.4.4'
main: me.iris.noxesiumapi.NoxesiumAPIPlugin
api-version: '1.21.10'
authors: [ Iris ]
description: A plugin and API making communicating with Noxesium clients easier.
website: https://github.com/Irisufus/NoxesiumAPI
